export { default as HeroCard } from './HeroCard';
export { default as ExperienceCard } from './ExperienceCard';
export { default as SkillsCard } from './SkillsCard';
export { default as CertificatCard } from './CertificateCard';
export { default as EducationCard } from './EducationCard';
export { default as ContactCard } from './ContactCard';
export { default as ProjectCard } from './OtherWorkCard';
export { default as LabCard } from './LabCard';
export { default as PrivacyCard } from './PrivacyCard';